### ISSUE TITLE
ma_pops_furniture:upcabinet has the same craft as minetest_game's trapdoor

### ISSUE THREAD

**Issue by R-0ne** [Gerold55/ma_pops_furniture#10]
hello, there is a conflict between your mod and minetest_game

in your mod :

--added craft
minetest.register_craft({
	output = 'ma_pops_furniture:upcabinet',
	recipe = {
	{'group:wood','group:wood','group:wood',},
	{'group:wood','group:wood','group:wood',},
	{'','','',},
	}
})

an in minetest_game :

minetest.register_craft({
	output = 'doors:trapdoor 2',
	recipe = {
		{'group:wood', 'group:wood', 'group:wood'},
		{'group:wood', 'group:wood', 'group:wood'},
		{'', '', ''},
	}
})

**Comment by Gerold55** [comment]
I believe that I have fixed it take a look and let me know if you run into any more issues.

**Comment by R-0ne** [comment]
i make a git pull, all is ok.
you can close the issue.

thank you very much
