### ISSUE TITLE
Port ABM to nodetimer

### ISSUE THREAD

**Issue by bell07** [Gerold55/ma_pops_furniture#4]
ABM's produces overhead in engine even no nodes are loaded. Therefore ABM's should not be used if the same functionality can be done by node-timers.

ma_pops_furniture:fireplace needs to be ported to node-times

**Comment by Gerold55** [comment]
I'm not sure how to do so sadly.

**Comment by bell07** [comment]
Which mod do you used for template?

**Comment by Gerold55** [comment]
NathanS. had done the ABM

**Comment by bell07** [comment]
I see, it is the https://github.com/Napiophelios/campfire, have the same issue, already in whynot oO

**Comment by bell07** [comment]
I wrote the nodetimer implementation for campfire in https://github.com/Napiophelios/campfire/commit/0b2d0c30113bf75583c5fa1b67b2a324d653029f
But it is not possible to apply the code 1:1 to ma_pops_furniture

**Comment by bell07** [comment]
done
