### ISSUE TITLE
functions.lua and sit.lua

### ISSUE THREAD

**Issue by acmgit** [Gerold55/ma_pops_furniture#5]
You have in sit.lua the globally functions:

function ma_pops_furniture.sit(pos, node, clicker)
function ma_pops_furniture.dig_chair(pos, node, meta, digger)
...
Ok, then you have in functions.lua the globally functions:

function ma_pops_furniture.sit(pos, node, clicker)
function ma_pops_furniture.dig_chair(pos, node, meta, digger)
...
Good, then in init.lua
dofile(minetest.get_modpath('ma_pops_furniture')..'/sit.lua')
dofile(minetest.get_modpath('ma_pops_furniture')..'/functions.lua')

Don't you write the functions in sit.lua and overwrite it in functions.lua on more time?

Greetings, Clyde.

**Comment by Gerold55** [comment]
I have fixed the issue... It should be proper now :)
